// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var TypedGlamor = require("bs-typed-glamor/src/TypedGlamor.bs.js");

var box = TypedGlamor.css(undefined, /* :: */[
      TypedGlamor.display(TypedGlamor.block),
      /* :: */[
        TypedGlamor.color(TypedGlamor.red),
        /* [] */0
      ]
    ]);

exports.box = box;
/* box Not a pure module */
